#! /bin/sh 
set -eux

#COSMO_LIBDIR=$(realpath "../../cosmopolitan/")
#HEADER_PATHS=$(realpath "./header_stubs")
COSMO_REPO=$(realpath "../../cosmopolitan")
COSMO_ISYSTEM=$(realpath "../../cosmopolitan/libc/isystem")

PREFIX=$(realpath "../../blead-cosmo")

if [ ! -d $COSMO_ISYSTEM ]; then
    echo "<<<SUPERCONFIGURE>>> cosmo isystem not found"
    exit 1
fi

echo "<<<SUPERCONFIGURE>>> cosmo isystem at $COSMO_REPO, assuming other files exist as well"

cd ../

echo "<<<SUPERCONFIGURE>>> Running Configure"

sh Configure \
    -Dprefix="$PREFIX" \
    -Dusedevel \
    -Duserelocatableinc \
    -Uused1 \
    -Dccflags="-static -nostdlib -nostdinc -fno-pie -no-pie -fno-omit-frame-pointer -pg -mnop-mcount -mno-tls-direct-seg-refs -I$COSMO_REPO -isystem $COSMO_ISYSTEM -include $COSMO_REPO/libc/integral/normalize.inc" \
    -Dldflags="-static -nostdlib -nostdinc -fno-pie -Wl,--gc-sections -fuse-ld=bfd -Wl,-T,$COSMO_REPO/o//ape/ape.lds $COSMO_REPO/o//libc/crt/crt.o $COSMO_REPO/o//ape/ape.o" \
    -Dlibs="$COSMO_REPO/o//cosmopolitan.a"

#-Dccflags="-static -nostdlib -nostdinc -fno-pie -no-pie -fno-omit-frame-pointer -pg -mnop-mcount -mno-tls-direct-seg-refs -I$HEADER_PATHS -include $COSMO_LIBDIR/cosmopolitan.h" \
#-Dldflags="-static -nostdlib -nostdinc -fno-pie -include $COSMO_LIBDIR/cosmopolitan.h -Wl,--gc-sections -fuse-ld=bfd -Wl,-T,$COSMO_LIBDIR/ape.lds -include $COSMO_LIBDIR/cosmopolitan.h $COSMO_LIBDIR/crt.o $COSMO_LIBDIR/ape.o" \
#-Dlibs="$COSMO_LIBDIR/cosmopolitan.a"
