#! /bin/sh 
set -eux

#COSMO_LIBDIR=$(realpath "../../cosmopolitan/")
#HEADER_PATHS=$(realpath "./header_stubs")
COSMO_REPO=$(realpath "../../cosmopolitan")
COSMO_GCC=$(realpath "../../cosmopolitan/o/third_party/gcc/bin/x86_64-linux-musl-gcc")
#COSMO_ISYSTEM=$(realpath "../../cosmopolitan/libc/isystem")
COSMO_ISYSTEM=$(realpath "dummy_isystem")
SYSROOT=$(realpath "../../sysroot")

PREFIX=$(realpath "../../blead-cosmo")

COSMO_MODE=${COSMO_MODE:=''};

if [ ! -d $COSMO_ISYSTEM ]; then
    echo "<<<SUPERCONFIGURE>>> cosmo isystem not found"
    exit 1
fi

echo "<<<SUPERCONFIGURE>>> cosmo isystem at $COSMO_REPO, assuming other files exist as well"

echo "<<<SUPERCONFIGURE>>> making prefix dirs"
mkdir -p "$PREFIX"
mkdir -p "$PREFIX/bin"

echo "<<<SUPERCONFIGURE>>> Building cosmo, COSMO_MODE=$COSMO_MODE"
make -C $COSMO_REPO -j4 MODE="$COSMO_MODE" o/$COSMO_MODE/cosmopolitan.a
make -C $COSMO_REPO -j4 MODE="$COSMO_MODE" o/$COSMO_MODE/libc/crt/crt.o
make -C $COSMO_REPO -j4 MODE="$COSMO_MODE" o/$COSMO_MODE/ape/ape.lds
make -C $COSMO_REPO -j4 MODE="$COSMO_MODE" o/$COSMO_MODE/ape/ape.o
make -C $COSMO_REPO -j4 MODE="$COSMO_MODE" o/$COSMO_MODE/ape/ape-no-modify-self.o
make -C $COSMO_REPO -j4 MODE="$COSMO_MODE" o/cosmopolitan.h

cd ../

echo "<<<SUPERCONFIGURE>>> Running Configure"

COSMO_MODE="$COSMO_MODE" COSMO_REPO="$COSMO_REPO" sh Configure -e \
    -Dprefix="$PREFIX" \
    -Dusedevel \
    -Doptimize="-Os" \
    -Dmyhostname="cosmo" \
    -Dmydomain="invalid" \
    -Dcf_by="cosmo" \
    -DDEBUGGING

